# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=255, verbose_name='Zip code')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('paternal_last_name', models.CharField(max_length=150, verbose_name='Paternal last name')),
                ('maternal_last_name', models.CharField(max_length=150, verbose_name='Maternal last name')),
                ('document_type', models.CharField(choices=[('DNI', 'National Identity Document'), ('RUC', 'Unique Taxpayer Registry'), ('PASSPORT', 'Passport'), ('FOREIGN_ID', 'Foreigner ID')], default='DNI', max_length=20, verbose_name='Document type')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Document number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID')),
                ('external_id', models.CharField(help_text='Unique external identifier for the applicant.', max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Validating'), (2, 'Approved'), (3, 'Rejected')], default=0, help_text='Current status of the applicant.')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['first_name', 'paternal_last_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=255, verbose_name='Zip code')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('paternal_last_name', models.CharField(max_length=150, verbose_name='Paternal last name')),
                ('maternal_last_name', models.CharField(max_length=150, verbose_name='Maternal last name')),
                ('document_type', models.CharField(choices=[('DNI', 'National Identity Document'), ('RUC', 'Unique Taxpayer Registry'), ('PASSPORT', 'Passport'), ('FOREIGN_ID', 'Foreigner ID')], default='DNI', max_length=20, verbose_name='Document type')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Document number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Inactive'), (3, 'Suspended'), (4, 'Expelled'), (5, 'Deceased')], default=0, help_text='Current status of the partner.')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['first_name', 'paternal_last_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('document_type', models.CharField(choices=[('DNI', 'National Identity Document'), ('RUC', 'Unique Taxpayer Registry'), ('PASSPORT', 'Passport'), ('FOREIGN_ID', 'Foreigner ID')], help_text='Type of identification document', max_length=20)),
                ('document_number', models.CharField(help_text='Document identification number', max_length=20)),
                ('first_name', models.CharField(help_text='First name of the prospect', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the prospect', max_length=100)),
                ('birth_date', models.DateField(help_text='Date of birth')),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Contacted'), (2, 'Interested'), (3, 'Qualified'), (4, 'Converted to Partner'), (5, 'Rejected'), (6, 'Lost')], default=0, help_text='Current status of the prospect')),
                ('source', models.CharField(default='landing_page', help_text='Source of the prospect registration', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when the prospect registered', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent when registered')),
                ('contacted_at', models.DateTimeField(blank=True, help_text='Date and time when prospect was first contacted', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the prospect')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerEmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('occupation', models.CharField(blank=True, help_text='Current occupation of the partner.', max_length=100)),
                ('profession', models.CharField(blank=True, help_text='Professional specialization or career.', max_length=100)),
                ('education_level', models.IntegerField(blank=True, choices=[(0, 'Primary Education'), (1, 'Secondary Education'), (2, 'Technical Education'), (3, 'University Education'), (4, 'Postgraduate'), (5, 'Doctorate')], help_text='Highest education level achieved.', null=True)),
                ('employment_type', models.IntegerField(blank=True, choices=[(0, 'Dependent Employee'), (1, 'Independent Worker'), (2, 'Services Provider'), (3, 'Consultant'), (4, 'Commission Agent')], help_text='Type of employment according to Peruvian labor law.', null=True)),
                ('is_currently_employed', models.BooleanField(default=False, help_text='Whether the partner is currently employed.')),
                ('workplace_name', models.CharField(blank=True, help_text='Name of the current workplace or company.', max_length=200)),
                ('workplace_address', models.CharField(blank=True, help_text='Address of the current workplace.', max_length=500)),
                ('other_workplace', models.CharField(blank=True, help_text='Additional or secondary workplace.', max_length=200)),
                ('job_position', models.CharField(blank=True, help_text='Current job position or title.', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department or area within the company.', max_length=100)),
                ('contract_type', models.IntegerField(blank=True, choices=[(0, 'Indefinite Term'), (1, 'Fixed Term'), (2, 'Part Time'), (3, 'Temporary'), (4, 'Seasonal'), (5, 'Training/Apprenticeship'), (6, 'Services Contract'), (7, 'Outsourcing')], help_text='Type of employment contract.', null=True)),
                ('contract_start_date', models.DateField(blank=True, help_text='Start date of current employment contract.', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='End date of contract (if applicable).', null=True)),
                ('work_schedule', models.IntegerField(blank=True, choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Flexible'), (3, 'Shift Work'), (4, 'Remote Work'), (5, 'Hybrid')], help_text='Type of work schedule.', null=True)),
                ('weekly_hours', models.PositiveIntegerField(blank=True, help_text='Number of weekly working hours.', null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Base salary amount in Peruvian Soles (PEN).', max_digits=10, null=True)),
                ('salary_frequency', models.IntegerField(blank=True, choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Biweekly'), (3, 'Monthly'), (4, 'Annual')], help_text='Frequency of salary payment.', null=True)),
                ('additional_income', models.DecimalField(blank=True, decimal_places=2, help_text='Additional income from bonuses, commissions, etc.', max_digits=10, null=True)),
                ('total_monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated monthly income.', max_digits=10, null=True)),
                ('work_phone', models.CharField(blank=True, help_text='Work phone number.', max_length=20)),
                ('work_email', models.EmailField(blank=True, help_text='Work email address.', max_length=254)),
                ('supervisor_name', models.CharField(blank=True, help_text='Name of direct supervisor or manager.', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about employment information.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('partner', models.OneToOneField(help_text='Partner associated with this employment information.', on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Partner Employment Information',
                'verbose_name_plural': 'Partner Employment Information',
                'ordering': ['partner__first_name', 'partner__paternal_last_name'],
            },
        ),
    ]
