# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.core.validators
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of the credit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Credit Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Interest Rate')),
                ('term_duration', models.PositiveIntegerField(help_text='Duration of the credit in months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Term Duration')),
                ('delinquency_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delinquency rate percentage for overdue payments.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Delinquency Rate')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('REFINANCED', 'Refinanced')], default='PENDING', help_text='Current status of the credit.', max_length=15, verbose_name='Status')),
                ('application_date', models.DateField(auto_now_add=True, help_text='Date when the credit was applied for.', verbose_name='Application Date')),
                ('approval_date', models.DateField(blank=True, help_text='Date when the credit was approved.', null=True, verbose_name='Approval Date')),
                ('disbursement_date', models.DateField(blank=True, help_text='Date when the credit was disbursed.', null=True, verbose_name='Disbursement Date')),
                ('payment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='MONTHLY', help_text='How often payments are due for this credit.', max_length=15, verbose_name='Payment Frequency')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated payment amount based on frequency.', max_digits=10, null=True, verbose_name='Payment Amount')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance.', max_digits=12, verbose_name='Outstanding Balance')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the credit.', verbose_name='Notes')),
                ('current_version', models.PositiveIntegerField(default=1, help_text='Current version number of the credit.', verbose_name='Current Version')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
                'ordering': ['-created'],
                'permissions': [('change_credit_status', 'Can change credit status'), ('approve_credit', 'Can approve credits'), ('reject_credit', 'Can reject credits')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount of credit requested.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Requested Amount')),
                ('proposed_interest_rate', models.DecimalField(decimal_places=2, help_text='Proposed annual interest rate percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Proposed Interest Rate')),
                ('requested_term_duration', models.PositiveIntegerField(help_text='Requested duration of the credit in months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Requested Term Duration')),
                ('requested_payment_frequency', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], help_text='Requested frequency for payments. If not specified, uses product default.', max_length=15, null=True, verbose_name='Requested Payment Frequency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ADDITIONAL_INFO', 'Additional Information Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the application.', max_length=20, verbose_name='Status')),
                ('estimated_payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated payment amount based on requested terms and frequency.', max_digits=10, null=True, verbose_name='Estimated Payment Amount')),
                ('payment_schedule', models.JSONField(blank=True, help_text='JSON representation of the generated payment schedule.', null=True, verbose_name='Payment Schedule')),
                ('possible_start_date', models.DateField(blank=True, help_text='Estimated date when the credit could start.', null=True, verbose_name='Possible Start Date')),
                ('proposed_delinquency_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Proposed delinquency rate percentage for overdue payments.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Proposed Delinquency Rate')),
            ],
            options={
                'verbose_name': 'Credit Application',
                'verbose_name_plural': 'Credit Applications',
                'ordering': ['-created'],
                'permissions': [('submit_creditapplication', 'Can submit credit applications'), ('review_creditapplication', 'Can review credit applications'), ('approve_creditapplication', 'Can approve credit applications')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('disbursement_amount', models.DecimalField(decimal_places=2, help_text='Amount to be disbursed.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Disbursement Amount')),
                ('scheduled_date', models.DateField(help_text='Date when the disbursement is scheduled.', verbose_name='Scheduled Date')),
                ('disbursement_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('ELECTRONIC_WALLET', 'Electronic Wallet'), ('OTHER', 'Other')], default='BANK_TRANSFER', help_text='Method used for disbursement.', max_length=20, verbose_name='Disbursement Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the disbursement.', max_length=15, verbose_name='Status')),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank for transfer.', max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, help_text='Account number for transfer.', max_length=50, verbose_name='Account Number')),
                ('account_holder_name', models.CharField(blank=True, help_text='Name of the account holder.', max_length=200, verbose_name='Account Holder Name')),
                ('check_number', models.CharField(blank=True, help_text='Check number if disbursement method is check.', max_length=50, verbose_name='Check Number')),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number.', max_length=100, verbose_name='Reference Number')),
                ('receipt_document', models.FileField(blank=True, help_text='Upload receipt or proof of disbursement.', null=True, upload_to='disbursements/receipts/%Y/%m/', verbose_name='Receipt Document')),
            ],
            options={
                'verbose_name': 'Credit Disbursement',
                'verbose_name_plural': 'Credit Disbursements',
                'ordering': ['-scheduled_date', '-created'],
                'permissions': [('approve_creditdisbursement', 'Can approve credit disbursements'), ('process_creditdisbursement', 'Can process credit disbursements')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditRefinanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('previous_outstanding_balance', models.DecimalField(decimal_places=2, help_text='Outstanding balance before rescheduling.', max_digits=12, verbose_name='Previous Outstanding Balance')),
                ('previous_term_remaining', models.PositiveIntegerField(help_text='Remaining months before rescheduling.', verbose_name='Previous Term Remaining (months)')),
                ('new_payment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='MONTHLY', help_text='New payment frequency.', max_length=15, verbose_name='New Payment Frequency')),
                ('new_term_duration', models.PositiveIntegerField(help_text='New total duration in months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='New Term Duration (months)')),
                ('new_interest_rate', models.DecimalField(decimal_places=2, help_text='New interest rate percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='New Interest Rate')),
                ('new_delinquency_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='New delinquency rate percentage for overdue payments.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='New Delinquency Rate')),
                ('additional_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Any additional amount added to the outstanding balance.', max_digits=12, verbose_name='Additional Amount')),
                ('start_date', models.DateField(help_text='Start date for new installments.', verbose_name='Start Date')),
                ('reason', models.TextField(help_text='Reason for the rescheduling.', verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the refinance request.', max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Credit Refinance Request',
                'verbose_name_plural': 'Credit Refinance Requests',
                'ordering': ['-created'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditRescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requested_term_extension', models.PositiveIntegerField(help_text='Number of months to extend the loan term.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Requested Term Extension (months)')),
                ('requested_interest_rate_adjustment', models.DecimalField(decimal_places=2, help_text='Percentage adjustment to the interest rate.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-5.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Requested Interest Rate Adjustment (%)')),
                ('reason', models.TextField(help_text='Reason for requesting the loan reschedule.', verbose_name='Reason for Reschedule')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the reschedule request.', max_length=15, verbose_name='Status')),
                ('request_date', models.DateField(auto_now_add=True, help_text='Date when the reschedule request was made.', verbose_name='Request Date')),
                ('review_date', models.DateField(blank=True, help_text='Date when the reschedule request was reviewed.', null=True, verbose_name='Review Date')),
                ('decision_date', models.DateField(blank=True, help_text='Date when decision was made on the reschedule request.', null=True, verbose_name='Decision Date')),
                ('requested_start_date', models.DateField(blank=True, help_text='Requested start date for the rescheduled credit installments.', null=True, verbose_name='Requested Start Date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the reschedule request.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Credit Reschedule Request',
                'verbose_name_plural': 'Credit Reschedule Requests',
                'ordering': ['-created'],
                'permissions': [('view_credit_summary', 'Can view credit summary information'), ('submit_creditreschedule', 'Can submit credit reschedule requests'), ('review_creditreschedule', 'Can review credit reschedule requests'), ('approve_creditreschedule', 'Can approve credit reschedule requests')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('installment_number', models.PositiveIntegerField(help_text='Sequential installment number in the amortization schedule.', verbose_name='Installment Number')),
                ('due_date', models.DateField(help_text='Date when this installment is due.', verbose_name='Due Date')),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Total installment amount (principal + interest).', max_digits=10, verbose_name='Installment Amount')),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Principal portion of the installment.', max_digits=10, verbose_name='Principal Amount')),
                ('interest_amount', models.DecimalField(decimal_places=2, help_text='Interest portion of the installment.', max_digits=10, verbose_name='Interest Amount')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Outstanding balance after this installment is paid.', max_digits=12, verbose_name='Balance After Payment')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('REFINANCED', 'Refinanced')], default='PENDING', help_text='Current status of the installment.', max_length=15, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, help_text='Date when this installment was actually paid.', null=True, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this installment.', verbose_name='Notes')),
                ('schedule_version', models.PositiveIntegerField(default=1, help_text='Version of the payment schedule this installment belongs to.', verbose_name='Schedule Version')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['credit', 'installment_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum credit amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Maximum credit amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Maximum Amount')),
                ('min_interest_rate', models.DecimalField(decimal_places=2, help_text='Minimum annual interest rate percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Minimum Interest Rate')),
                ('max_interest_rate', models.DecimalField(decimal_places=2, help_text='Maximum annual interest rate percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Maximum Interest Rate')),
                ('interest_type', models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], default='FIXED', help_text='Type of interest rate.', max_length=10, verbose_name='Interest Type')),
                ('min_term_duration', models.PositiveIntegerField(help_text='Minimum duration in months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Minimum Term Duration')),
                ('max_term_duration', models.PositiveIntegerField(help_text='Maximum duration in months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Maximum Term Duration')),
                ('payment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='MONTHLY', help_text='How often payments are due.', max_length=15, verbose_name='Payment Frequency')),
                ('min_delinquency_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum delinquency rate percentage for overdue payments.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Minimum Delinquency Rate')),
                ('max_delinquency_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum delinquency rate percentage for overdue payments.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Maximum Delinquency Rate')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_type', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product type is active.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
