# Generated by Django 5.2.3 on 2025-11-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False, 'ordering': ['name'], 'permissions': [('view_chatbot_settings', 'Can view chatbot settings'), ('change_chatbot_settings', 'Can change chatbot settings')], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
