# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('execution_date', models.DateTimeField(blank=True, help_text='Date and time when the campaign will be executed.', null=True, verbose_name='Execution Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('SENDING', 'Sending'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the campaign.', max_length=20, verbose_name='Status')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='TELEGRAM', help_text='Communication channel for campaign notifications.', max_length=20, verbose_name='Channel')),
                ('use_payment_link', models.BooleanField(default=False, help_text='Include payment link in campaign notifications.', verbose_name='Use Payment Link')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Average cost per notification for this campaign.', max_digits=12, null=True, verbose_name='Average Cost')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Target collection amount for the campaign.', max_digits=12, null=True, verbose_name='Target Amount')),
                ('is_processing', models.BooleanField(default=False, help_text='Indicates if the campaign is currently being processed.', verbose_name='Is Processing')),
                ('last_execution_at', models.DateTimeField(blank=True, help_text='Date and time of the last execution attempt.', null=True, verbose_name='Last Execution At')),
                ('execution_count', models.PositiveIntegerField(default=0, help_text='Number of times this campaign has been executed.', verbose_name='Execution Count')),
                ('last_execution_result', models.TextField(blank=True, help_text='Result message from the last execution attempt.', null=True, verbose_name='Last Execution Result')),
                ('campaign_type', models.CharField(choices=[('GROUP', 'Group-based Campaign'), ('FILE', 'File-based Campaign')], default='GROUP', help_text='Type of campaign (auto-populated).', max_length=20, verbose_name='Campaign Type')),
                ('whatsapp_personalize_messages', models.BooleanField(default=True, help_text='Personalize each WhatsApp message to avoid spam detection.', verbose_name='Personalize WhatsApp Messages')),
                ('whatsapp_include_stop_command', models.BooleanField(default=True, help_text='Include "write STOP to stop receiving messages" in WhatsApp messages.', verbose_name='Include STOP Command')),
                ('whatsapp_avoid_unsolicited_links', models.BooleanField(default=True, help_text='Avoid sending payment links in the first message to prevent spam flags.', verbose_name='Avoid Unsolicited Links')),
                ('whatsapp_group_by_region', models.BooleanField(default=False, help_text='Group contacts by region to avoid messaging many international numbers simultaneously.', verbose_name='Group By Region')),
                ('whatsapp_target_response_rate', models.DecimalField(decimal_places=2, default=30.0, help_text='Target response rate percentage (recommended: 30%).', max_digits=5, verbose_name='Target Response Rate')),
                ('file', models.FileField(blank=True, help_text='Uploaded CSV or Excel file with contacts and amounts.', null=True, upload_to='campaigns/csv/%Y/%m/%d/', verbose_name='File')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Valid')], default='PENDING', help_text='Status of contacts validation.', max_length=20, verbose_name='Validation Status')),
                ('validation_result', models.JSONField(blank=True, help_text='Detailed validation results and errors.', null=True, verbose_name='Validation Result')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date and time when validation was completed.', null=True, verbose_name='Validated At')),
                ('total_contacts', models.PositiveIntegerField(default=0, help_text='Total number of contacts in the CSV file.', verbose_name='Total Contacts')),
                ('valid_contacts', models.PositiveIntegerField(default=0, help_text='Number of valid contacts after validation.', verbose_name='Valid Contacts')),
                ('invalid_contacts', models.PositiveIntegerField(default=0, help_text='Number of invalid contacts after validation.', verbose_name='Invalid Contacts')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign CSV/Excel File',
                'verbose_name_plural': 'Campaign CSV/Excel Files',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2, help_text='Priority level of the group.', verbose_name='Priority')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('partners', models.ManyToManyField(blank=True, help_text='Partners included in this group.', related_name='campaign_groups', to='partners.partner', verbose_name='Partners')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('execution_date', models.DateTimeField(blank=True, help_text='Date and time when the campaign will be executed.', null=True, verbose_name='Execution Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('SENDING', 'Sending'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the campaign.', max_length=20, verbose_name='Status')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='TELEGRAM', help_text='Communication channel for campaign notifications.', max_length=20, verbose_name='Channel')),
                ('use_payment_link', models.BooleanField(default=False, help_text='Include payment link in campaign notifications.', verbose_name='Use Payment Link')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Average cost per notification for this campaign.', max_digits=12, null=True, verbose_name='Average Cost')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Target collection amount for the campaign.', max_digits=12, null=True, verbose_name='Target Amount')),
                ('is_processing', models.BooleanField(default=False, help_text='Indicates if the campaign is currently being processed.', verbose_name='Is Processing')),
                ('last_execution_at', models.DateTimeField(blank=True, help_text='Date and time of the last execution attempt.', null=True, verbose_name='Last Execution At')),
                ('execution_count', models.PositiveIntegerField(default=0, help_text='Number of times this campaign has been executed.', verbose_name='Execution Count')),
                ('last_execution_result', models.TextField(blank=True, help_text='Result message from the last execution attempt.', null=True, verbose_name='Last Execution Result')),
                ('campaign_type', models.CharField(choices=[('GROUP', 'Group-based Campaign'), ('FILE', 'File-based Campaign')], default='GROUP', help_text='Type of campaign (auto-populated).', max_length=20, verbose_name='Campaign Type')),
                ('whatsapp_personalize_messages', models.BooleanField(default=True, help_text='Personalize each WhatsApp message to avoid spam detection.', verbose_name='Personalize WhatsApp Messages')),
                ('whatsapp_include_stop_command', models.BooleanField(default=True, help_text='Include "write STOP to stop receiving messages" in WhatsApp messages.', verbose_name='Include STOP Command')),
                ('whatsapp_avoid_unsolicited_links', models.BooleanField(default=True, help_text='Avoid sending payment links in the first message to prevent spam flags.', verbose_name='Avoid Unsolicited Links')),
                ('whatsapp_group_by_region', models.BooleanField(default=False, help_text='Group contacts by region to avoid messaging many international numbers simultaneously.', verbose_name='Group By Region')),
                ('whatsapp_target_response_rate', models.DecimalField(decimal_places=2, default=30.0, help_text='Target response rate percentage (recommended: 30%).', max_digits=5, verbose_name='Target Response Rate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Group associated with this campaign.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CSVContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(help_text="Contact's full name.", max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, help_text="Contact's email address.", max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text="Contact's phone number.", max_length=20, null=True, verbose_name='Phone')),
                ('telegram_id', models.CharField(blank=True, help_text="Contact's Telegram ID or username.", max_length=50, null=True, verbose_name='Telegram ID')),
                ('document_number', models.CharField(blank=True, help_text="Contact's document number (DNI, RUC, etc.).", max_length=20, null=True, verbose_name='Document Number')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to collect from this contact.', max_digits=12, verbose_name='Amount')),
                ('additional_data', models.JSONField(blank=True, help_text='Additional fields from CSV (key-value pairs).', null=True, verbose_name='Additional Data')),
                ('is_valid', models.BooleanField(default=False, help_text='Whether this contact passed validation.', verbose_name='Is Valid')),
                ('validation_errors', models.JSONField(blank=True, help_text='List of validation errors for this contact.', null=True, verbose_name='Validation Errors')),
                ('row_number', models.PositiveIntegerField(help_text='Row number in the original CSV file.', verbose_name='Row Number')),
                ('campaign', models.ForeignKey(help_text='CSV campaign this contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='csv_contacts', to='campaigns.campaigncsvfile', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'CSV Contact',
                'verbose_name_plural': 'CSV Contacts',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['campaign', 'is_valid'], name='campaigns_c_campaig_a77b1e_idx'), models.Index(fields=['document_number'], name='campaigns_c_documen_6f0775_idx'), models.Index(fields=['phone'], name='campaigns_c_phone_663f1d_idx'), models.Index(fields=['telegram_id'], name='campaigns_c_telegra_c6a505_idx')],
            },
        ),
    ]
