# Generated by Django 5.2.3 on 2025-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_failed',
            field=models.PositiveIntegerField(default=0, help_text='Total number of notifications that failed to send.', verbose_name='Total Failed'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_sent',
            field=models.PositiveIntegerField(default=0, help_text='Total number of notifications sent successfully.', verbose_name='Total Sent'),
        ),
        migrations.AddField(
            model_name='campaigncsvfile',
            name='total_failed',
            field=models.PositiveIntegerField(default=0, help_text='Total number of notifications that failed to send.', verbose_name='Total Failed'),
        ),
        migrations.AddField(
            model_name='campaigncsvfile',
            name='total_sent',
            field=models.PositiveIntegerField(default=0, help_text='Total number of notifications sent successfully.', verbose_name='Total Sent'),
        ),
    ]
