# Generated by Django 5.2.3 on 2026-04-13 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_notification_metrics'),
        ('notifications', '0002_messagetemplate_campaign_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message_template',
            field=models.ForeignKey(blank=True, help_text="Specific template to use for this campaign's notifications.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.messagetemplate', verbose_name='Message Template'),
        ),
        migrations.AddField(
            model_name='campaigncsvfile',
            name='message_template',
            field=models.ForeignKey(blank=True, help_text="Specific template to use for this campaign's notifications.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.messagetemplate', verbose_name='Message Template'),
        ),
    ]
