# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(help_text='Primary key of the related object.')),
                ('status', models.CharField(help_text='New status value.', max_length=50, verbose_name='Status')),
                ('previous_status', models.CharField(blank=True, help_text='Previous status value.', max_length=50, verbose_name='Previous Status')),
                ('note', models.TextField(blank=True, help_text='Optional note about the status change.', verbose_name='Note')),
                ('content_type', models.ForeignKey(help_text='Content type of the related object.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_status_content_1b1e90_idx'), models.Index(fields=['created'], name='core_status_created_68b695_idx')],
            },
        ),
    ]
