# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp')], default='TELEGRAM', help_text='Communication channel (Telegram or WhatsApp)', max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Telegram chat ID for this conversation', max_length=100, null=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username of the user', max_length=100)),
                ('whatsapp_phone', models.CharField(blank=True, help_text='WhatsApp phone number for this conversation', max_length=20, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending Authentication'), (2, 'Authenticated'), (3, 'Active'), (4, 'Closed'), (5, 'Blocked')], default=1, help_text='Current status of the conversation')),
                ('authenticated', models.BooleanField(default=False, help_text='Whether the user has been authenticated')),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Last interaction timestamp')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context data for the conversation (pending actions, state, etc.)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='Partner associated with this conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Agent Conversation',
                'verbose_name_plural': 'Agent Conversations',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AGENT', 'Agent'), ('SYSTEM', 'System')], help_text='Who sent this message', max_length=10)),
                ('message', models.TextField(help_text='Message content')),
                ('intent', models.CharField(blank=True, choices=[('GREETING', 'Greeting'), ('AUTHENTICATION', 'Authentication'), ('PARTNER_DETAIL', 'Partner Detail'), ('ACCOUNT_STATEMENT', 'Account Statement'), ('LIST_CREDITS', 'List Credits'), ('CREDIT_DETAIL', 'Credit Detail'), ('CREATE_TICKET', 'Create Support Ticket'), ('UPLOAD_RECEIPT', 'Upload Payment Receipt'), ('HELP', 'Help'), ('GOODBYE', 'Goodbye'), ('UNKNOWN', 'Unknown')], help_text='Detected intent of the message', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (API responses, file info, etc.)')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.agentconversation')),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'ordering': ['created'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel', 'TELEGRAM'), ('telegram_chat_id__isnull', False)), models.Q(('channel', 'WHATSAPP'), ('whatsapp_phone__isnull', False)), _connector='OR'), name='channel_identifier_required'),
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_chat_id__isnull', False)), fields=('telegram_chat_id',), name='unique_telegram_chat_id'),
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_phone__isnull', False)), fields=('whatsapp_phone',), name='unique_whatsapp_phone'),
        ),
    ]
