# Generated by Django 5.2.3 on 2026-03-24 06:16

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Template name (as registered in Meta)', max_length=100)),
                ('category', models.CharField(help_text='Template category (MARKETING, UTILITY, AUTHENTICATION)', max_length=50)),
                ('language', models.CharField(default='es', help_text='Template language code', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused')], default='PENDING', help_text='Meta approval status', max_length=20)),
                ('body', models.TextField(help_text='Template body text')),
                ('meta_template_id', models.CharField(blank=True, help_text='Template ID assigned by Meta', max_length=100, null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this template has been sent')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], help_text='Delivery status for outbound WhatsApp messages', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, help_text='WhatsApp message ID for delivery tracking', max_length=100, null=True),
        ),
    ]
