# Generated by Django 5.2.3 on 2026-04-08 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_update_intent_to_tool_name'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentconversation',
            name='channel_identifier_required',
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='web_session_id',
            field=models.CharField(blank=True, help_text='Web session ID for testing purposes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agentconversation',
            name='channel',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('WEB', 'Web (Testing)')], default='TELEGRAM', help_text='Communication channel (Telegram or WhatsApp)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel', 'TELEGRAM'), ('telegram_chat_id__isnull', False)), models.Q(('channel', 'WHATSAPP'), ('whatsapp_phone__isnull', False)), models.Q(('channel', 'WEB'), ('web_session_id__isnull', False)), _connector='OR'), name='channel_identifier_required'),
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('web_session_id__isnull', False)), fields=('web_session_id',), name='unique_web_session_id'),
        ),
    ]
