from django.urls import path

from apps.credits import api, views

app_name = "apps.credits"

urlpatterns = [
    # ProductType URLs
    path(
        "product-types/",
        views.ProductTypeListView.as_view(),
        name="product_type_list",
    ),
    path(
        "product-types/create/",
        views.ProductTypeCreateView.as_view(),
        name="product_type_create",
    ),
    path(
        "product-types/<int:pk>/",
        views.ProductTypeDetailView.as_view(),
        name="product_type_detail",
    ),
    path(
        "product-types/<int:pk>/edit/",
        views.ProductTypeUpdateView.as_view(),
        name="product_type_update",
    ),
    path(
        "product-types/<int:pk>/delete/",
        views.ProductTypeDeleteView.as_view(),
        name="product_type_delete",
    ),
    # Product URLs
    path(
        "products/",
        views.ProductListView.as_view(),
        name="product_list",
    ),
    path(
        "products/create/",
        views.ProductCreateView.as_view(),
        name="product_create",
    ),
    path(
        "products/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "products/<int:pk>/edit/",
        views.ProductUpdateView.as_view(),
        name="product_update",
    ),
    path(
        "products/<int:pk>/delete/",
        views.ProductDeleteView.as_view(),
        name="product_delete",
    ),
    # Credit URLs
    path(
        "credits/",
        views.CreditListView.as_view(),
        name="credit_list",
    ),
    path(
        "credits/create/",
        views.CreditCreateView.as_view(),
        name="credit_create",
    ),
    path(
        "credits/<int:pk>/",
        views.CreditDetailView.as_view(),
        name="credit_detail",
    ),
    path(
        "credits/<int:pk>/edit/",
        views.CreditUpdateView.as_view(),
        name="credit_update",
    ),
    path(
        "credits/<int:pk>/delete/",
        views.CreditDeleteView.as_view(),
        name="credit_delete",
    ),
    path(
        "credits/<int:pk>/change-status/",
        views.CreditChangeStatusView.as_view(),
        name="credit_change_status",
    ),
    # Credit Application URLs
    path(
        "credit-applications/",
        views.CreditApplicationListView.as_view(),
        name="credit_application_list",
    ),
    path(
        "credit-applications/create/",
        views.CreditApplicationCreateView.as_view(),
        name="credit_application_create",
    ),
    path(
        "credit-applications/<int:pk>/",
        views.CreditApplicationDetailView.as_view(),
        name="credit_application_detail",
    ),
    path(
        "credit-applications/<int:pk>/edit/",
        views.CreditApplicationUpdateView.as_view(),
        name="credit_application_update",
    ),
    path(
        "credit-applications/<int:pk>/delete/",
        views.CreditApplicationDeleteView.as_view(),
        name="credit_application_delete",
    ),
    path(
        "credit-applications/<int:pk>/change-status/",
        views.CreditApplicationChangeStatusView.as_view(),
        name="credit_application_change_status",
    ),
    path(
        "credit-applications/<int:pk>/payment-schedule-pdf/",
        views.CreditApplicationPaymentSchedulePDFView.as_view(),
        name="credit_application_payment_schedule_pdf",
    ),
    # Credit Reschedule Request URLs
    path(
        "credit-reschedule-requests/",
        views.CreditRescheduleRequestListView.as_view(),
        name="credit_reschedule_request_list",
    ),
    path(
        "credit-reschedule-requests/create/",
        views.CreditRescheduleRequestCreateView.as_view(),
        name="credit_reschedule_request_create",
    ),
    path(
        "credit-reschedule-requests/<int:pk>/",
        views.CreditRescheduleRequestDetailView.as_view(),
        name="credit_reschedule_request_detail",
    ),
    path(
        "credit-reschedule-requests/<int:pk>/edit/",
        views.CreditRescheduleRequestUpdateView.as_view(),
        name="credit_reschedule_request_edit",
    ),
    path(
        "credit-reschedule-requests/<int:pk>/delete/",
        views.CreditRescheduleRequestDeleteView.as_view(),
        name="credit_reschedule_request_delete",
    ),
    # Credit Refinance Request URLs
    path(
        "credit-refinance-requests/",
        views.CreditRefinanceRequestListView.as_view(),
        name="credit_refinance_request_list",
    ),
    path(
        "credit-refinance-requests/create/",
        views.CreditRefinanceRequestCreateView.as_view(),
        name="credit_refinance_request_create",
    ),
    path(
        "credit-refinance-requests/<int:pk>/",
        views.CreditRefinanceRequestDetailView.as_view(),
        name="credit_refinance_request_detail",
    ),
    path(
        "credit-refinance-requests/<int:pk>/edit/",
        views.CreditRefinanceRequestUpdateView.as_view(),
        name="credit_refinance_request_edit",
    ),
    path(
        "credit-refinance-requests/<int:pk>/delete/",
        views.CreditRefinanceRequestDeleteView.as_view(),
        name="credit_refinance_request_delete",
    ),
    # Credit Disbursement URLs
    path(
        "disbursements/",
        views.CreditDisbursementListView.as_view(),
        name="disbursement_list",
    ),
    path(
        "disbursements/create/",
        views.CreditDisbursementCreateView.as_view(),
        name="disbursement_create",
    ),
    path(
        "disbursements/<int:pk>/",
        views.CreditDisbursementDetailView.as_view(),
        name="disbursement_detail",
    ),
    path(
        "disbursements/<int:pk>/edit/",
        views.CreditDisbursementUpdateView.as_view(),
        name="disbursement_update",
    ),
    path(
        "disbursements/<int:pk>/delete/",
        views.CreditDisbursementDeleteView.as_view(),
        name="disbursement_delete",
    ),
    path(
        "disbursements/<int:pk>/change-status/",
        views.CreditDisbursementChangeStatusView.as_view(),
        name="disbursement_change_status",
    ),
    # API URLs
    path(
        "api/credits/<int:credit_id>/summary/",
        api.CreditSummaryAPIView.as_view(),
        name="api_credit_summary",
    ),
    path(
        "api/products/<int:product_id>/summary/",
        api.ProductSummaryAPIView.as_view(),
        name="api_product_summary",
    ),
]
