# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.core.validators
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('due_date', models.DateField(help_text='Date when the payment is due.', verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial Payment'), ('WAIVED', 'Waived'), ('APPEALED', 'Under Appeal'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the payment.', max_length=15, verbose_name='Status')),
                ('period_year', models.PositiveIntegerField(help_text='Year of the contribution period.', verbose_name='Period Year')),
                ('period_month', models.PositiveIntegerField(help_text='Month of the contribution period.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Period Month')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-period_year', '-period_month', 'partner'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('due_date', models.DateField(help_text='Date when the payment is due.', verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial Payment'), ('WAIVED', 'Waived'), ('APPEALED', 'Under Appeal'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the payment.', max_length=15, verbose_name='Status')),
                ('penalty_type', models.CharField(choices=[('LATE_PAYMENT', 'Late Payment'), ('INCORRECT_DECLARATION', 'Incorrect Declaration'), ('MISSING_DECLARATION', 'Missing Declaration'), ('ADMINISTRATIVE', 'Administrative Penalty'), ('TAX_VIOLATION', 'Tax Violation')], help_text='Type of penalty.', max_length=25, verbose_name='Penalty Type')),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Date when the penalty was issued.', verbose_name='Issue Date')),
                ('description', models.TextField(help_text='Description of the violation or reason for penalty.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-issue_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('due_date', models.DateField(help_text='Date when the payment is due.', verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial Payment'), ('WAIVED', 'Waived'), ('APPEALED', 'Under Appeal'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the payment.', max_length=15, verbose_name='Status')),
                ('period_year', models.PositiveIntegerField(help_text='Year of the social security period.', verbose_name='Period Year')),
                ('period_month', models.PositiveIntegerField(help_text='Month of the social security period.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Period Month')),
            ],
            options={
                'verbose_name': 'Social Security',
                'verbose_name_plural': 'Social Security',
                'ordering': ['-period_year', '-period_month', 'partner'],
                'managed': False,
            },
        ),
    ]
