# Generated by Django 5.2.3 on 2026-04-16 23:18

import django.core.validators
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceInitialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('initial_contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount contributed before system implementation.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Initial Contribution Amount')),
                ('initial_social_security_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total social security amount paid before system implementation.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Initial Social Security Amount')),
                ('cut_off_date', models.DateField(help_text='Date from which the system starts tracking detailed payments.', verbose_name='Cut-off Date')),
            ],
            options={
                'verbose_name': 'Compliance Initial Balance',
                'verbose_name_plural': 'Compliance Initial Balances',
                'managed': False,
            },
        ),
    ]
