# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('payment_number', models.CharField(help_text='Unique payment identifier or number.', max_length=50, verbose_name='Payment Number')),
                ('payment_date', models.DateField(help_text='Date when the payment was actually made.', verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('ELECTRONIC_WALLET', 'Electronic Wallet'), ('CULQI_ONLINE', 'Online Payment (Culqi)'), ('OTHER', 'Other')], default='CASH', help_text='Method used for the payment.', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, check number, or transaction ID.', max_length=100, verbose_name='Reference Number')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PAID', help_text='Status of this payment.', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment.', verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data specific to the payment concept.', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentConceptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the concept receiving the payment.')),
                ('amount_applied', models.DecimalField(decimal_places=2, help_text='Amount from the payment applied to this concept.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount Applied')),
                ('application_date', models.DateField(auto_now_add=True, help_text='Date when the payment was applied to this concept.', verbose_name='Application Date')),
                ('allocation_type', models.CharField(choices=[('FULL', 'Full Payment'), ('PARTIAL', 'Partial Payment'), ('OVERPAYMENT', 'Overpayment')], default='FULL', help_text='Type of allocation.', max_length=20, verbose_name='Allocation Type')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment allocation.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Payment Concept Allocation',
                'verbose_name_plural': 'Payment Concept Allocations',
                'ordering': ['payment', 'application_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MagicPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('token', models.CharField(help_text='Unique short token for the payment link URL.', max_length=12, unique=True, verbose_name='Token')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount to be paid (sum of all included debts).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total Amount')),
                ('expires_at', models.DateTimeField(help_text='Date and time when this link expires.', verbose_name='Expires At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Status of the payment link.', max_length=20, verbose_name='Status')),
                ('used_at', models.DateTimeField(blank=True, help_text='Date and time when this link was used for payment.', null=True, verbose_name='Used At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Additional metadata including debt concepts: {'debts': [{'type': 'installment', 'id': 123, 'amount': 387.00}, ...]}", verbose_name='Metadata')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATED', 'Automated')], default='MANUAL', help_text='Source or campaign that generated this link.', max_length=20, verbose_name='Source')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Partner for whom this link was created.', on_delete=django.db.models.deletion.PROTECT, related_name='magic_payment_links', to='partners.partner')),
                ('payment', models.ForeignKey(blank=True, help_text='Payment associated with this link if used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_links', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Magic Payment Link',
                'verbose_name_plural': 'Magic Payment Links',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['partner'], name='payments_ma_partner_264629_idx'), models.Index(fields=['token'], name='payments_ma_token_bf63d1_idx'), models.Index(fields=['status'], name='payments_ma_status_f3689f_idx'), models.Index(fields=['expires_at'], name='payments_ma_expires_5bd5c7_idx'), models.Index(fields=['-created'], name='payments_ma_created_c8ed8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('receipt_file', models.FileField(help_text='Uploaded receipt file (PDF, JPG, PNG).', upload_to='payment_receipts/%Y/%m/%d/', verbose_name='Receipt File')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount shown on the receipt.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('payment_date', models.DateField(help_text='Date when the payment was made according to the receipt.', verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Validation status of the receipt.', max_length=20, verbose_name='Validation Status')),
                ('validation_notes', models.TextField(blank=True, help_text='Notes from the employee who validated the receipt.', verbose_name='Validation Notes')),
                ('validated_at', models.DateTimeField(blank=True, help_text='Date and time when the receipt was validated.', null=True, verbose_name='Validated At')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the receipt.', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Partner who uploaded the receipt.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='partners.partner')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Employee who validated this receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_receipts', to='team.employee')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['partner'], name='payments_pa_partner_620dbd_idx'), models.Index(fields=['status'], name='payments_pa_status_338458_idx'), models.Index(fields=['payment_date'], name='payments_pa_payment_402617_idx'), models.Index(fields=['-created'], name='payments_pa_created_a19ae1_idx')],
            },
        ),
    ]
