# Generated by Django 5.2.3 on 2026-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_whatsapp_response',
            field=models.BooleanField(default=False, help_text='This comment was sent as a WhatsApp response to the partner', verbose_name='WhatsApp Response'),
        ),
    ]
