# Generated by Django 5.2.3 on 2026-05-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_add_is_whatsapp_response_to_ticketcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcomment',
            name='is_internal',
        ),
    ]
