# Generated by Django 5.2.3 on 2025-11-13 14:24

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('campaign_id', models.PositiveIntegerField(verbose_name='Campaign ID')),
                ('recipient_id', models.PositiveIntegerField(verbose_name='Recipient ID')),
                ('notification_type', models.CharField(choices=[('SCHEDULED', 'Scheduled Notification')], help_text='Type of notification sent (before due date, on due date, etc.).', max_length=20, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='WHATSAPP', help_text='Communication channel used for the notification.', max_length=20, verbose_name='Channel')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the notification.', max_length=20, verbose_name='Status')),
                ('recipient_email', models.EmailField(blank=True, help_text='Email address where the notification was sent.', max_length=254, null=True, verbose_name='Recipient Email')),
                ('recipient_phone', models.CharField(blank=True, help_text='Phone number where the notification was sent.', max_length=20, null=True, verbose_name='Recipient Phone')),
                ('recipient_telegram_id', models.CharField(blank=True, help_text='Telegram ID where the notification was sent.', max_length=50, null=True, verbose_name='Recipient Telegram ID')),
                ('message_content', models.TextField(blank=True, help_text='Content of the notification message.', null=True, verbose_name='Message Content')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Date and time when the notification is scheduled to be sent.', null=True, verbose_name='Scheduled At')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Date and time when the notification was actually sent.', null=True, verbose_name='Sent At')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the notification failed to send.', null=True, verbose_name='Error Message')),
                ('total_debt_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total debt amount for the partner at the time of notification.', max_digits=12, null=True, verbose_name='Total Debt Amount')),
                ('included_payment_link', models.BooleanField(default=False, help_text='Whether a payment link was included in the notification.', verbose_name='Included Payment Link')),
                ('payment_link_url', models.URLField(blank=True, help_text='URL of the payment link included in the notification.', null=True, verbose_name='Payment Link URL')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of attempts made to send this notification.', verbose_name='Attempt Count')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Date and time of the last attempt to send the notification.', null=True, verbose_name='Last Attempt At')),
                ('campaign_type', models.ForeignKey(limit_choices_to={'model__in': ('campaign', 'campaigncsvfile')}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notifications', to='contenttypes.contenttype', verbose_name='Campaign Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('recipient_type', models.ForeignKey(limit_choices_to={'model__in': ('partner', 'csvcontact')}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_as_recipient', to='contenttypes.contenttype', verbose_name='Recipient Type')),
            ],
            options={
                'verbose_name': 'Campaign Notification',
                'verbose_name_plural': 'Campaign Notifications',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['campaign_type', 'campaign_id'], name='notificatio_campaig_04ded3_idx'), models.Index(fields=['recipient_type', 'recipient_id'], name='notificatio_recipie_006fa1_idx'), models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_fb8567_idx'), models.Index(fields=['channel', 'status'], name='notificatio_channel_2ff48c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_type', models.CharField(choices=[('SCHEDULED', 'Scheduled Notification')], help_text='Type of notification this template is for.', max_length=20, verbose_name='Template Type')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='WHATSAPP', help_text='Communication channel for this template.', max_length=20, verbose_name='Channel')),
                ('subject', models.CharField(blank=True, help_text='Subject line for email notifications (optional).', max_length=200, null=True, verbose_name='Subject')),
                ('message_body', models.TextField(help_text='Template body with placeholders: {partner_name}, {debt_amount}, {payment_link}, {due_date}, {company_name}, {contact_phone}', verbose_name='Message Body')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently active.', verbose_name='Is Active')),
                ('whatsapp_template_name', models.CharField(blank=True, help_text='Name of the approved WhatsApp Business template (if using templates).', max_length=100, null=True, verbose_name='WhatsApp Template Name')),
                ('include_payment_button', models.BooleanField(default=False, help_text='Whether to include a payment button/link in the message.', verbose_name='Include Payment Button')),
                ('payment_button_text', models.CharField(default='Pagar ahora', help_text='Text to display on the payment button/link.', max_length=50, verbose_name='Payment Button Text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['template_type', 'channel', 'is_active'], name='notificatio_templat_4170d3_idx')],
                'unique_together': {('template_type', 'channel', 'is_active')},
            },
        ),
    ]
