# Generated by Django 5.2.3 on 2026-04-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='campaign_type',
            field=models.CharField(choices=[('GROUP', 'Group-based Campaign'), ('FILE', 'File-based Campaign')], default='GROUP', help_text='Type of campaign this template is for (GROUP or FILE).', max_length=20, verbose_name='Campaign Type'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='whatsapp_variables',
            field=models.CharField(blank=True, help_text="Comma-separated list of context variables to send to Meta in the exact order (e.g. 'full_name,amount'). Meta uses positions {{1}}, {{2}}.", max_length=255, verbose_name='WhatsApp Variables'),
        ),
    ]
